### ISSUE TITLE
Unwrap through hiera

### ISSUE THREAD

**Issue by karolina1819** [TraGicCode/tragiccode-azure_key_vault#105]
Hi TraGicCode,

I would like to use this module mostly through hiera. Using alias function works fine when resource is handling Sensitive data type, but I haven't been able to find a way to proceed with those that are not (Special case 2 described in documentation). Do you have a suggestion how to handle this through hiera? Maybe I'm missing something.

Thanks,
Karolina

**Comment by TraGicCode** [comment]
Hey @karolina1819 ,

I think I understand what you are talking about but to make sure, can you provide a code sample of your use case?

**Comment by karolina1819** [comment]
Hi @TraGicCode,

I'm sorry for the late reply.
Here is code sample:

In data/common.yaml:

`prometheus::rabbitmq_exporter::rabbit_password: "%{alias('rabbitmq-exporter-rabbit-password')}"`

In site/role/manifests/rabbitnode.pp:

```
class role::rabbitnode (
) {
  include prometheus::rabbitmq_exporter
}
```

So, we just include prometheus module in the class and provide necessary data through hiera.

The output from puppet agent is:

```
root@rabbitmq:~# puppet agent -t
Info: Using environment 'rabbitmq'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Class[Prometheus::Rabbitmq_exporter]: parameter 'rabbit_password' expects a String value, got Sensitive[String] (file: /etc/puppetlabs/code/environments/rabbitmq/site/role/manifests/rabbitnode.pp, line: 7, column: 3) on node rabbitmq-01.qa.msp
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Let me know if you need more info.

**Comment by TraGicCode** [comment]
Hey @karolina1819 ,

min not at a computer at the moment but can’t you just call the “unwrap function” on the return value of the Alias function?

**Comment by TraGicCode** [comment]
Hey @karolina1819,

I asked on the puppet slack and this was  the response i got to this.

```
No.
From within a Hiera data file, you can only use this small set of "interpolation functions", not arbitrary Puppet functions:
https://www.puppet.com/docs/puppet/7/hiera_merging.html#interpolation_functions (edited) 
[8:20](https://puppetcommunity.slack.com/archives/C0W298S9G/p1674699601316729)
Also, the Sensitive type (which is what would be unwrapped) isn't really a primitive known to Hiera. It's a Puppet type. So a value can't be Sensitive while it's in Hiera.
It can be looked up then converted to Sensitive for use in Puppet code, but while it's in Hiera, there's no concept of "Sensitive".
https://www.puppet.com/docs/puppet/7/hiera_merging.html#setting_lookup_options_to_refine_the_result_of_a_lookup-make-hiera-return-data-by-casting
```

This module is currently returning a Sensitive type from both the puppet function and hiera lookup function. In order to support this there would need to be some sort of feature request done along with an idea on how it might look like or work to support this scenario.

At this point, your only option would be to declare the hidden dependencies ( the parameters ) instead of using this shortcut mechanism.
