### ISSUE TITLE
Error retrieving access token with "Temporarily throttled, too many requests" message

### ISSUE THREAD

**Issue by bwarren18** [TraGicCode/tragiccode-azure_key_vault#30]
Hello we are seeing an error on the puppet agent with description: "Temporarily throttled, too many requests".

We checked the puppet master log and it points to the exception occurring on line 14 in azure.rb

We ran the curl commands from here on the puppet master and they worked.  We were able to retrieve the access token and secret in ssh in plaintext.
https://stackoverflow.com/questions/51440297/how-to-set-the-value-of-an-azure-keyvault-secret-using-curl

Kind Regards.

**Comment by bwarren18** [comment]
The other error in puppetserver.log was line 17 in lookup.rb

We are using Puppet 2019.0.0 aka v6.  The agent version is 6.0.2.

Our hiera.yaml contains:
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: xxxxxxxxxxxxxxxxxx
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-02-01'

Our manifest contains:
$secret_user = Deferred("azure_key_vault::secret", ['vaultname', 'secretname', {
  metadata_api_version => '2018-02-01',
  vault_api_version    => '2016-10-01',
}])

**Comment by bwarren18** [comment]
Hi TraGicCode,

We just started using Puppet about 1 week ago and are testing.

1. We have 13 nodes.
2. We have 1 secret in hiera.
3. I do not know the difference between the two, we started with Puppet 6.
4. We started with module version 1.0.0
5. I am not sure I understand what log you want to query.  Can you provide an example?

Thank you.

**Comment by TraGicCode** [comment]
Hey @bwarren18 ,

Thanks for replying.

1. Are you currently pulling secrets using hiera's automatic parameter lookup feature? ( https://puppet.com/docs/puppet/5.2/hiera_automatic.html )? When you've been writing your code is your expecting been that all secrets will be retrieved by making a call to the following puppet 4 function VIA your puppet manifests?

```puppet
$secret_user = Deferred("azure_key_vault::secret", ['vaultname', 'secretname', {
metadata_api_version => '2018-02-01',
vault_api_version => '2016-10-01',
}])
```

1. There should be some log or activity log for your azure key vault that, i would think, gives more detail on who requests what secrets and what secret they are requesting.

**Comment by bwarren18** [comment]
Hi @TraGicCode,

1.  We have 2 key lookups in our manifest and two secrets in the same Azure Key Vault.  The only difference is the secretname.

I modified our manifest, replacing "::secret" with "::lookup" so it is now:
`$secret_1 = Deferred("azure_key_vault::lookup", [''KeyVaultName''', 'Secret1', {
  metadata_api_version => '2018-02-01',
  vault_api_version    => '2016-10-01',
}])

$secret_2 = Deferred("azure_key_vault::lookup", [''KeyVaultName'''', 'Secret2', {
  metadata_api_version => '2018-02-01',
  vault_api_version    => '2016-10-01',
}])`

2. I enabled Diagnostic Logs on the Azure Key Vault.  The JSON log shows 3 entries that being with:

>     "operationName": "Authentication",
>     "resultType": "Success",
> 
> "operationName": "SecretGet",
>     "resultType": "Success",
> 
> "operationName": "SecretGet",
>     "resultType": "Success",

**Comment by bwarren18** [comment]
Hi @TraGicCode ,

To enable diagnostic logs, I went into the key vault blade in Azure.  Then clicked on "Turn on diagnostics to collect the following data." I selected Archive to a storage account and provided the name of an storage account to use.  I also checked the Send to Log Analytics box and selected a workspace.  I then checked the Log type 'AuditEvent' and set the retention to 365 days.  I then went into the storage account, blob, filtered for container name "insights-logs-auditevent".  I then navigated down to the newest JSON log file and downloaded it.  

You can then also view it in Log Analytics by querying: 
search * | where Category=="AuditEvent"  and OperationName == "SecretGet"

1. Ok I reverted back to calling azure_keyvault::secret in our manifest.
2. Ok I commented out those lines in hiera.yaml with the # character.

I then reverted back to not using the deferred functions.
The error went away and we are able to unwrap the secrets successfully.

The issue can be closed.
Thank you very much for the plugin and help!
- bwarren
