### ISSUE TITLE
Evaluation Error: Unknown function: 'azure_key_vault::secret'.

### ISSUE THREAD

**Issue by xenon8** [TraGicCode/tragiccode-azure_key_vault#38]
Hi, we are getting this error (Evaluation Error: Unknown function: 'azure_key_vault::secret'.) when we include the secret function in our code as below:

file { 'C:\\temp\\test.xml':
    ensure  => file,
    content => azure_key_vault::secret('puppetvault','oursecret', {
      metadata_api_version => '2018-02-01',
      vault_api_version    => '2016-10-01',
    }),

we have updated the puppetfile and we have attempted to run it manually by installing the module directly on a puppet agent and using a apply command.

Each time we get the error. We are quite new to puppet so I accept if we have done some simply wrong but we are unable to see why this is not working; given that we have taken the code directly from description of the module.

We have also test with other module functions (such as base64 from the stdlib) and we are able to use these; so we are very confused why the secret function is just not being found by Puppet.

We are using Puppet Agent 5.5.4 on a Windows 2016 box. I have also tested it against a CentOS 7.3 box.

In both cases the module is definitely installed as I can see it in the module directory and I can list it using: puppet module list.

**Comment by TraGicCode** [comment]
Hey @xenon8 ,

Thanks for opening up an issue and i'm sorry you're having issues.  I was unable to reproduce your issue on my end. i performed the following.


1. Provisioned new windows 2016 vm
2. Installed puppet version 5.5.4
3. Tried to run your script but it was syntax errors so i fixed it to be this

```
file { 'C:\temp\test.xml':
ensure => file,
content => azure_key_vault::secret('puppetvault','oursecret', {
metadata_api_version => '2018-02-01',
vault_api_version => '2016-10-01',
}),
}
```

4. Puppet found the azure_key_vault::secret function with no issues when i did a puppet run.

Can you provide detailed steps of what your are doing so we can figure out where thing might be going wrong?  

Are you running puppet in an elevated administrator prompt so that it finds the modules at the right location?

**Comment by xenon8** [comment]
Hi TraGicCode,

Thanks very much for getting back to me and full marks for provisioning a vm! :)

I have done the following on a Puppet Agent box (to reduce the complexity of using it from the puppet master):

puppet module install tragiccode-azure_key_vault --version 1.0.0

Then I did a puppet module list:
![royalts_2018-11-23_09-41-07](https://user-images.githubusercontent.com/44359413/48936863-208fc200-ef04-11e8-9156-a5320e8e18d6.png)

Then I did a puppet apply -e:
![royalts_2018-11-23_09-44-30](https://user-images.githubusercontent.com/44359413/48936963-7f553b80-ef04-11e8-9b64-48ea4355bb3b.png)

Now I fully expect the function to fail as the key vault name referenced doesn't exist, but this shouldn't matter at the moment, as I just want to confirm it can find function.

I have attached the module I have just created for this test.
[test_key_vault_issue.zip](https://github.com/TraGicCode/tragiccode-azure_key_vault/files/2610226/test_key_vault_issue.zip)

I was running from a Admin PS console.

**Comment by TraGicCode** [comment]
Hey @xenon8 ,

Are you calling my function from a module you created?  If so i think you have to put my module as a dependency in your metadata.json for your module to utilize the `azure_key_vaule::secret` function.  

Try calling it from a simple manifest file like below and see what happens:

test.pp
```
file { 'C:\temp\test.xml':
ensure => file,
content => azure_key_vault::secret('puppetvault','oursecret', {
metadata_api_version => '2018-02-01',
vault_api_version => '2016-10-01',
}),
}
```

puppet apply test.pp --verbose

**Comment by xenon8** [comment]
Hi TraGicCode,

Indeed you are right; Thank you so much! I am extremely grateful for you helping me out. Sorry it was such a basic thing.

Kudos, and thanks very much for putting this module together.

**Comment by TraGicCode** [comment]
Hey @xenon8 ,

No problem thanks for posting an issue!  Please post anything else that comes up even if you believe it's something you might be doing wrong with this module.

Cheers!

**Comment by shterm** [comment]
my step is such:
first: puppet module install tragiccode-azure_key_vault --version 1.0.2
second: write site.pp, such as
file { '/tmp/a':
ensure => file,
content => azure_key_vault::secret('puppetvault','oursecret', {
metadata_api_version => '2018-02-01',
vault_api_version => '2016-10-01',
}),
}
third: int client run  puppet agent --test
![image](https://user-images.githubusercontent.com/57557997/68919625-be336f80-07ad-11ea-872b-6339acc151cb.png)

**Comment by xenon8** [comment]
Hi @shterm,

Did you add the module into the metadata.json file?

```
"dependencies": [
    {
      "name": "tragiccode/azure_key_vault",
      "version_requirement": ">= 1.0.0 < 5.0.0"
    },
```

**Comment by shterm** [comment]
@xenon8 maybe my version is too lower。 upgrade my version to puppet5(old version is 3.6)，it`s normal working
![image](https://user-images.githubusercontent.com/57557997/68930053-8ab20e80-07c8-11ea-8974-0f749e7db685.png)
