### ISSUE TITLE
Failed with Bolt

### ISSUE THREAD

**Issue by yesoreyeram** [TraGicCode/tragiccode-azure_key_vault#55]
I am trying to use this module with bolt targetting remote node. But this fails with the following error.

`valuation Error: Error while evaluating a Function Call, Failed to open TCP connection to 169.254.169.254:80 (Connection refused - connect(2) for "169.254.169.254" port 80) (file: /etc/puppet/site-modules/roles/manifests/mymodule.pp, line: 5, column: 13) on node X.X.X.X`

My code is very simple as 

 ```
 $secret = azure_key_vault::secret('myvault', 'PassMain', {
    metadata_api_version => '2018-04-02',
    vault_api_version    => '2016-10-01',
  })
  $rewraped_secret = Sensitive("${secret.unwrap}")
  notice($rewraped_secret)
```

If i execute the same command using puppet apply that works fine in that remote node. Any  suggestions?

**Comment by TraGicCode** [comment]
Hey @yesoreyeram ,

Are you able to do the following for me.

1. Puppet apply
a. Debug logs
b. Code
c. Command line used to run puppet apply
1. Bolt
a. Debug logs
b. Code
c. Command line used to run bolt

**NOTE: Please redact or obfuscate any sensitive data**

**Comment by TraGicCode** [comment]
Hey @yesoreyeram,

Is this still an issue or did you figure it out?

**Comment by yesoreyeram** [comment]
Yes still this is an issue. But sorry, I couldn't get you the traces.  I afraid I can't get you that anytime soon as I am not actively workig on that part.

I am closing this issue. If require i will reopen later or feel free to reopen.
