### ISSUE TITLE
azure keyvault integration with puppet

### ISSUE THREAD

**Issue by THG-onkar** [TraGicCode/tragiccode-azure_key_vault#63]
i am facing issue. trying to integrate azure keyvault with puppet, i have setup manage identity between azure key vault and puppet master vm, after that using puppet mainfest code am trying to acces that secrate in puppet.

$secret = azure_key_vault::secret('demo-test1', 'onkar', {
  metadata_api_version => '2018-04-02',
  vault_api_version    => '2016-10-01',
})

$rewraped_secret = Sensitive("password: ${secret.unwrap}")

file { 'C:\\DataForApplication.secret':
  content   => $rewraped_secret,
  ensure    => file,
}

Facing error when retriving data in client node Now, run the following command on the client node to retrieve the configurations.

sudo /opt/puppetlabs/bin/puppet agent --test

![image](https://user-images.githubusercontent.com/63608474/85314076-8eccaa00-b4d6-11ea-8824-77b098ffcc59.png)

**Comment by TraGicCode** [comment]
Hey @THG-onkar ,

Can you confirm if the puppet server has the module installed into the production environment?

**Comment by THG-onkar** [comment]
module is install but i am not sure in last line its showing another path and result module not installed.
Please help me on this.

![image](https://user-images.githubusercontent.com/63608474/85363364-61b3e200-b53e-11ea-9fc4-aa27241c068d.png)

**Comment by TraGicCode** [comment]
Hey @THG-onkar ,

It looks like you installed the module in your users home directory and not using the sudo command.  Can you try installing the module with sudo and see if this resolves your issue?

Thanks!

**Comment by THG-onkar** [comment]
Hi @TraGicCode  iI have tryed to install modules with super user (sudo) but its showing error puppet not found... but i am trying to install Nginx and it work properly
showing following error with sudo... please help me on this
![image](https://user-images.githubusercontent.com/63608474/85613578-a68f6400-b677-11ea-80b6-c7f15f05c032.png)

**Comment by THG-onkar** [comment]
hi @TraGicCode  its work and the code deploy sucessfully but its not showing the secret i have change code still its not showing the secret, how can i check the secrets?

code wich i used in manifest -:
$secret = azure_key_vault::secret('demo-test1', 'onkar', {
  metadata_api_version => '2018-04-02',
  vault_api_version    => '2016-10-01',
})
notice($secret)
output-:
![image](https://user-images.githubusercontent.com/63608474/85620537-8d8bb080-b681-11ea-9ec5-308482366ff6.png)

second code-

$important_secret = azure_key_vault::secret('demo-test1', 'onkar', {
  metadata_api_version => '2018-04-02',
  vault_api_version    => '2016-10-01',
})

output-:
![image](https://user-images.githubusercontent.com/63608474/85620698-c592f380-b681-11ea-8dc7-cde98e76eeb1.png)

**Comment by TraGicCode** [comment]
Hey @THG-onkar ,

Calling the `notice()` function only puts the log into the puppet server logs and doesn't go to stdout.  If you want it to go to stdout so you can see it during your puppet run, like you are attempting to do, you should use the notify resource like the following:

```
notify { 'display-secret':
  message => $secret.unwrap,
}
```

**Comment by TraGicCode** [comment]
Closing this as this doesn’t seem like a bug from the way the conversation is going.

**Comment by THG-onkar** [comment]
@TraGicCode i have use notify function but its not work please help me
