### ISSUE TITLE
facing issue my puppet integration with key vault

### ISSUE THREAD

**Issue by THG-onkar** [TraGicCode/tragiccode-azure_key_vault#64]
Hi @TraGicCode 

my code is work sucessfully but not able to verify where the secrete is store i am using following code for retrive secrete and i have add notify secrete fuction but its showing error please help me on this.

$secret = azure_key_vault::secret('production-vault', 'important-secret', {
  metadata_api_version => '2018-04-02',
  vault_api_version    => '2016-10-01',
})
notice($secret)

for stdout i am using following code
notify { 'display-secret':
  message => $secret.unwrap,
}

i have merge this code with first code but its showing error

can you please give me one example if i want to setup one SQL connection string for particular in puppet code how can i setup this retrive function methon on that code and how it work and how we can integrate this code

Thanks!

**Comment by TraGicCode** [comment]
Can you show the error log?

**Comment by TraGicCode** [comment]
Closing this.
