### ISSUE TITLE
Feature suggestion: Implement back-off to avoid throttling

### ISSUE THREAD

**Issue by dowlingw** [TraGicCode/tragiccode-azure_key_vault#70]
Suggest implementing throttling in the KeyVault client to ensure clients deal with being rate limited against the service limits: https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling#how-to-throttle-your-app-in-response-to-service-limits

As discussed in #69 - automatic parameter lookup can very quickly generate hundreds of lookups against KeyVault, and larger sites using the `azure_key_vault::secret` secret may be able to hit this also.

Implementing rate limiting in `TragicCode::Azure::get_secret` will make this solution more resilient.

**Comment by TraGicCode** [comment]
Hey @dowlingw ,

Can you think of any other alternatives? I thought about suggesting to the user to always ensure that this is the last location in the configured hierarchy to look to make it the last location to be checked.  Do you think this is reasonable/makes sense?  I guess this could cause an issue if someone is doing something where they have 2 locations in which a secret can be ( maybe if they are doing a secrets migration???? ).  

What are your thoughts?

The only other alternative i can think of would be some sort of "if you hit the rate limit wait 10 seconds and then try again" which seems hacky 🤷

**Comment by dowlingw** [comment]
No getting around this one I think :(

The only remotely related thing I came across was the default_hierarchy key but this only applies to the module layer and doesn't really address this problem: https://puppet.com/docs/puppet/7.5/hiera_config_yaml_5.html#the-default_hierarchy-key

Otherwise I was going to have a quick look at similar providers for AWS Secret Manager/Hashicorp Vault in case they have any similar strategies.

#69 was the only other thing I was able to come up with.

**Comment by TraGicCode** [comment]
Hey @dowlingw ,

Are you on the puppet community slack?
