### ISSUE TITLE
For resource User password setup via key vault

### ISSUE THREAD

**Issue by namithcc** [TraGicCode/tragiccode-azure_key_vault#82]
Hi ,

Could you please help me ,

for user resource, azure key vault password nit working as expected 
User is getting created, password not accepting. For file resource perfectly working.

**Comment by TraGicCode** [comment]
Hey @namithcc ,

You will need to provide more information in order for me or anyone else to help you.  Can you please provide

1. The puppet code you are using
2. Module version
3. the error message during the puppet run

**Comment by TraGicCode** [comment]
Closing this until more information can be provided.
