### ISSUE TITLE
Loading Key Vaults dynamically 

### ISSUE THREAD

**Issue by sriharim** [TraGicCode/tragiccode-azure_key_vault#83]
We are creating Key Vault names like 
PROD-KEY-VAULT-0001
DEV-KEY-VAULT-3458
UAT-KEY-VAULT-7893

Due to uniqueness, we are adding random number to Key Vault name.

how do I load random Key Vault names in Hiera.yaml ?

**Comment by TraGicCode** [comment]
Hey,

min the documentation there is an example of pulling the vault name from a fact

`- name: 'Azure Key Vault Secrets from trusted fact'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: "%{trusted.extensions.pp_environment}"
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^azure_.*'
        - '^.*_password$'
        - '^password.*' 
`

mas far as I know, I’m not aware of another way to do this.  Does this work for you?

responding from a mobile device so code formatting might be terrible!

**Comment by sriharim** [comment]
Thanks for quick response.

I have two Key Vaults for one environment. How do I configure in Hiera.yaml.

**Comment by TraGicCode** [comment]
> Thanks for quick response.
> 
> I have two Key Vaults for one environment. How do I configure in Hiera.yaml.

Like mentioned above, you could add a fact that determines what vault a puppet node uses as shown in the above code snippet and module documentation

**Comment by TraGicCode** [comment]
Hey @sriharim ,

Did the above answer help you? I will close this issue in 1 week if there isn’t a response.

thank you
