### ISSUE TITLE
Add create/update functionality

### ISSUE THREAD

**Issue by sshipway** [TraGicCode/tragiccode-azure_key_vault#98]
It would be great to be able to create and update secrets using these functions.

This would allow Puppet to fully deploy a system, storing newly-created credentials into a Keyvault for use elsewhere (a better solution than using exported resources for this purpose)
Puppet could also then be used to manage OS passwords (such as root, oracle, etc) and rotate them when they are too old, storing the new password in the keyvault.

**Comment by TraGicCode** [comment]
> It would be great to be able to create and update secrets using these functions.

Can you provide a concrete example of this? Are you talking about specifically within the usage of a bolt task/plan itself?
